// src/shared/constants/endpoints.constants.ts
export const Endpoints = {
  USER: '/api/user',
  USER_PREFERENCES: '/api/user/preferences',
  LISTINGS: '/api/listings',
  LISTING_BY_ID: (id: string) => `/api/listings/${id}`,
  LISTING_REGENERATE: (id: string) => `/api/listings/${id}/regenerate`,
  LISTING_ARCHIVE: (id: string) => `/api/listings/${id}/archive`,
  LISTING_RESTORE: (id: string) => `/api/listings/${id}/restore`,
  PLANS: '/api/plans',
  CHECKOUT: '/api/checkout',
  SUBSCRIPTION: '/api/subscription',
  SUBSCRIPTION_CANCEL: '/api/subscription/cancel',
  SUBSCRIPTION_UPGRADE: '/api/subscription/upgrade',
  NOTIFICATIONS: '/api/notifications',
  NOTIFICATION_READ: (id: string) => `/api/notifications/${id}/read`,
  NOTIFICATIONS_READ_ALL: '/api/notifications/read-all',
  FEATURE_FLAGS: '/api/feature-flags',
  SUPPORT: '/api/support',
  REFERRAL: '/api/referral',
  STRIPE_WEBHOOK: '/api/webhooks/stripe',
  CRON_DAILY: '/api/cron/daily',
  ADMIN_DASHBOARD: '/api/admin/dashboard',
  ADMIN_USERS: '/api/admin/users',
  ADMIN_USER_BY_ID: (id: string) => `/api/admin/users/${id}`,
  ADMIN_PLANS: '/api/admin/plans',
  ADMIN_PLAN_BY_ID: (id: string) => `/api/admin/plans/${id}`,
  ADMIN_FEATURE_FLAGS: '/api/admin/feature-flags',
  ADMIN_FEATURE_FLAG_BY_KEY: (key: string) => `/api/admin/feature-flags/${key}`,
  ADMIN_SETTINGS: '/api/admin/settings',
  ADMIN_CMS: '/api/admin/cms',
  ADMIN_CMS_BY_KEY: (key: string) => `/api/admin/cms/${key}`,
  ADMIN_CMS_UPLOAD: '/api/admin/cms/upload',
  ADMIN_GROWTH_REFERRAL: '/api/admin/growth/referral',
  ADMIN_GROWTH_LOYALTY: '/api/admin/growth/loyalty',
  ADMIN_PROMOTIONS: '/api/admin/growth/promotions',
} as const;
